import { describe, expect, it } from "vitest";
import { generateCompiledFileContent, resolveOutputPath } from "#src/cli/emitter.js";
import type { CodeGenResult } from "#src/core/codegen/index.js";

describe("generateCompiledFileContent()", () => {
  it("generates a valid compiled file with header and __zcMkv wrapper", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef:
        'function safeParse_test(input){\nvar __issues=[];\nif(typeof input!=="string"){__issues.push({code:"invalid_type",expected:"string",received:typeof input,path:[],message:"Expected string"});}\nif(__issues.length>0)return{success:false,error:{issues:__issues}};\nreturn{success:true,data:input};\n}',
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
    );

    expect(content).toContain("// AUTO-GENERATED by zod-compiler");
    expect(content).toContain("// Source: ./test.ts");
    expect(content).toContain("function safeParse_test(input)");
    // Uses __zcMkv factory for Zod compatibility (installs methods on the source schema)
    expect(content).toMatch(
      /__zcMkv\(safeParse_test,\(__src_validateTest as any\)\.schema,(?:__fc_\d+|null)\)/,
    );
    // Imports source schema (needed for zodCompat)
    expect(content).toContain('import { validateTest as __src_validateTest } from "./test"');
  });

  it("generates multiple schemas in one file", () => {
    const result1: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_a(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };
    const result2: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_b(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [
        { exportName: "validateA", codegenResult: result1, refEntries: [] },
        { exportName: "validateB", codegenResult: result2, refEntries: [] },
      ],
      "./multi.ts",
    );

    expect(content).toContain("export const validateA");
    expect(content).toContain("export const validateB");
    expect(content).toContain("__zcMkv(safeParse_a,");
    expect(content).toContain("__zcMkv(safeParse_b,");
  });

  it("includes zod config import and __zcMsg inside IIFE", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
    );

    expect(content).toContain(
      'import { config as __zodCompilerConfig, ZodRealError as __zcZodError } from "zod"',
    );
    // __zcMsg, __zcMkv, __zcFin are declared at file level (once per file)
    expect(content).toContain("var __zcMsg=__zodCompilerConfig().localeError;");
    expect(content).toContain("function __zcMkv(fn,schema,fc)");
    expect(content).toContain("function __zcFin(e,d)");
  });

  it("always imports source schemas for zodCompat", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
    );

    // Source schemas are always imported now (for zodCompat)
    expect(content).toContain('import { validateTest as __src_validateTest } from "./test"');
  });
});

describe("generateCompiledFileContent() — zodCompat: false", () => {
  it("omits source import when no refEntries (enables tree-shaking)", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef: "function safeParse_test(input){\nreturn{success:true,data:input};\n}",
      refCount: 0,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result, refEntries: [] }],
      "./test.ts",
      { zodCompat: false },
    );

    expect(content).not.toContain("__src_validateTest");
    expect(content).not.toContain('from "./test"');
  });

  it("still imports source schemas when fallbacks exist", () => {
    const result: CodeGenResult = {
      code: "/* zod-compiler */",
      functionDef:
        "function safeParse_test(input){\nvar __issues=[];\nreturn{success:true,data:input};\n}",
      refCount: 1,
      usedHelpers: new Set(),
    };

    const content = generateCompiledFileContent(
      [
        {
          exportName: "validateUser",
          codegenResult: result,
          refEntries: [{ schema: {}, accessPath: '.shape["slug"]' }],
        },
      ],
      "./schemas.ts",
      { zodCompat: false },
    );

    expect(content).toContain('import { validateUser as __src_validateUser } from "./schemas"');
    expect(content).toContain("export const validateUser = /* @__PURE__ */");
    expect(content).toMatch(/__zcMkv\(safeParse_test,null,(?:__fc_\d+|null)\)/);
  });
});

describe("resolveOutputPath()", () => {
  it("defaults to .compiled.ts when no output flag", () => {
    const result = resolveOutputPath("src/schemas.ts", undefined);
    expect(result).toBe("src/schemas.compiled.ts");
  });

  it("uses output flag as-is when it's a file path", () => {
    const result = resolveOutputPath("src/schemas.ts", "out/validators.ts");
    expect(result).toBe("out/validators.ts");
  });

  it("puts compiled file inside directory when output ends with /", () => {
    const result = resolveOutputPath("src/schemas.ts", "out/");
    expect(result).toContain("out/");
    expect(result).toContain("schemas.compiled.ts");
  });
});
